apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: back
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: backend
        image: karanmanhas22/6month_harsh_backend:latest
        ports:
        - containerPort: 3015